if vim.g.vscode then
  require "vscode"
  return
end

-- Actual nvim
require "user.launch"
require "user.utils"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.transparent"
spec "user.devicons"
spec "user.treesitter"
spec "user.copilot"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.navic"
-- spec "user.breadcrumbs"
spec "user.null-ls"
-- spec "user.illuminate"
spec "user.telescope"
spec "user.telescope-tabs"
-- spec "user.nvimtree"
spec "user.neotree"
spec "user.lualine"
spec "user.whichkey"
spec "user.buffermanager"
spec "user.cmp"
spec "user.autopairs"
spec "user.comment"
spec "user.gitsigns"
spec "user.neogit"
spec "user.diffview"
-- spec "user.indentline"
-- spec "user.alpha"
spec "user.netrw"
spec "user.project"
-- spec "user.toggleterm"
spec "user.bufdelete"
spec "user.multicursor"
spec "user.incline"
require "user.lazy"
