require "launch.launch"
require "launch.options"
require "launch.keymaps"
require "launch.autocmds"
spec "launch.colorscheme"
spec "launch.devicons"
spec "launch.treesitter"
spec "launch.mason"
spec "launch.schemastore"
spec "launch.lspconfig"
spec "launch.cmp"
spec "launch.telescope"
spec "launch.none-ls"
spec "launch.illuminate"
spec "launch.gitsigns"
spec "launch.whichkey"
spec "launch.nvimtree"
spec "launch.comment"
spec "launch.lualine"
spec "launch.navic"
-- spec "launch.breadcrumbs"
spec "launch.harpoon"
-- spec "launch.neotest"
spec "launch.autopairs"
spec "launch.neogit"
-- spec "launch.alpha"
spec "launch.project"
spec "launch.indentline"
spec "launch.toggleterm"
require "launch.lazy"
